<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mqManage.proto

namespace GPBMetadata;

class MqManage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Í
mqManage.protomqManage"ž
PublishRequest
appName (	
taskName (	8
taskData (2&.mqManage.PublishRequest.TaskDataEntry/
TaskDataEntry
key (	
value (	:8",
PublishResponse
code (
msg (	"ž
ConsumeRequest
appName (	
taskName (	8
taskData (2&.mqManage.ConsumeRequest.TaskDataEntry/
TaskDataEntry
key (	
value (	:8",
ConsumeResponse
code (
msg (	2Š
MqManage>
publish.mqManage.PublishRequest.mqManage.PublishResponse>
consume.mqManage.ConsumeRequest.mqManage.ConsumeResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

