<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mqManage.proto

namespace MqManage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mqManage.ConsumeRequest</code>
 */
class ConsumeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appName = 1;</code>
     */
    protected $appName = '';
    /**
     * Generated from protobuf field <code>string taskName = 2;</code>
     */
    protected $taskName = '';
    /**
     * Generated from protobuf field <code>map<string, string> taskData = 3;</code>
     */
    private $taskData;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appName
     *     @type string $taskName
     *     @type array|\Google\Protobuf\Internal\MapField $taskData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MqManage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appName = 1;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->appName;
    }

    /**
     * Generated from protobuf field <code>string appName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->appName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string taskName = 2;</code>
     * @return string
     */
    public function getTaskName()
    {
        return $this->taskName;
    }

    /**
     * Generated from protobuf field <code>string taskName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskName($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> taskData = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTaskData()
    {
        return $this->taskData;
    }

    /**
     * Generated from protobuf field <code>map<string, string> taskData = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTaskData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->taskData = $arr;

        return $this;
    }

}

